title: Jack Bulson
author:
  name: Jack Bulson
  email: jacktbulson@gmail.com
description: >
  Gameplay Programmer @ Sumo Newcastle


minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,         user_url: "https://github.com/BulsonJ" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jack-b-2a4195115/" }


show_excerpts: false # set to true to show excerpts on the homepage

# Build settings
baseurl: /minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
